name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to gitlab repo
      run: docker login --username taa97 --password P@55word!0719186679 registry.gitlab.com

    - name: Build Docker image
      run: docker build -t registry.gitlab.com/taa971/docker_demo .

    - name: Push Docker image
      run: docker push registry.gitlab.com/taa971/docker_demo